version: 2.1
jobs:
  build:
    working_directory: /usr/src/Slicer-Liver
    docker:
      - image: olevs/slicer-build-ubuntu2004
    steps:
      - checkout
      # Rely on the Slicer version in the Docker image
      #- run:
      #    name: Update 3D Slicer
      #    command: |
      #      cd /usr/src/Slicer
      #      git checkout .
      #      git pull
            
      # Rebuilding Slicer may take a long time
      # For now, just use the build files already present in the Docker image
      #- run:
      #    name: Build 3D Slicer
      #    environment:
      #      BUILD_TOOL_FLAGS: "-j3"
      #    command: |
      #      ../Slicer-build/BuildSlicer.sh
      
      # Not needed, as this is done by the checkout step
      #- run:
      #    name: Update Liver extension
      #    command: |
      #      git clone https://github.com/ALive-research/Slicer-Liver.git
      #      cd /usr/src/Slicer-Liver
      #      git checkout .
      #      git pull
      
      - run:
          name: Configure Liver extension
          command: |
            mkdir /usr/src/Slicer-Liver-Build
            cd /usr/src/Slicer-Liver-Build
            cmake -DCMAKE_BUILD_TYPE:STRING=Release -DSlicer_DIR:PATH=/usr/src/Slicer-build/Slicer-build ../Slicer-Liver
            
      - run:
          name: Build Liver extension
          environment:
            BUILD_TOOL_FLAGS: "-j1"
          command: |
            cd /usr/src/Slicer-Liver-Build
            make
            

      - run:
          name: Run X virtual framebuffer
          command: Xvfb :99 -screen 0 640x480x8 -nolisten tcp
          background: true
      - run:
          name: Run Liver plugin tests
          command: |
            cd /usr/src/Slicer-Liver-Build
            ctest
